version: '3.7'
services:
  nginx:
    image: 'nginx:alpine'
    volumes:
      - './:/project'
      - './config/docker/site.conf:/etc/nginx/conf.d/default.conf'
    ports:
      - '2511:80'
    depends_on:
      - php

  php:
    build: 'config/docker/php'
    image: 'php:8-fpm-alpine'
    volumes:
      - './:/project'

  composer:
    image: 'composer:latest'
    volumes:
      - './:/project'
    working_dir: '/project'
